### ISSUE TITLE
Inclusion in Eclipse

### ISSUE THREAD

**Issue by wimjongman** [end3r/Gamedev-Canvas-workshop#15]
Hello wonderful people,

I am working on Eclipse bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=514294

I was wondering if I could use your game to include as an example. For this to be used inside Eclipse Open Source, the licensing must be clear. Is this open-source, and if so, what is the license?

**Comment by wimjongman** [comment]
I found the license.  https://github.com/end3r/Gamedev-Canvas-workshop/blob/gh-pages/LICENSE

**Comment by end3r** [comment]
Sure, go ahead!

It would be awesome if you could share a link afterwards if/when the inclusion goes public in any way, thanks!

**Comment by wimjongman** [comment]
Sure! I will share details once I'm done.

**Comment by wimjongman** [comment]
How about this:

![image](https://user-images.githubusercontent.com/180969/144136423-b81a02f6-d825-4fb7-8b0f-ebf9c60c03a4.png)

**Comment by end3r** [comment]
Looks good :)

**Comment by wimjongman** [comment]
It is included in Eclipse 4.23

https://www.eclipse.org/eclipse/news/4.23/pde.php#javascript

Thanks!

**Comment by end3r** [comment]
sweet, thanks for letting me know!

**Comment by end3r** [comment]
FYI https://end3r.com/blog/breakout-eclipse/
