### ISSUE TITLE
Speed of the ball

### ISSUE THREAD

**Issue by Odinsson25** [end3r/Gamedev-Canvas-workshop#17]
Where to edit the movement speed of the ball?

**Comment by end3r** [comment]
@FynnT076 Moving the ball is in the [second lesson of the tutorial](https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Move_the_ball) - `dx` and `dy` represent the speed in both directions, so the current value of `2` can be increased to make the ball move faster.
