### ISSUE TITLE
Want to add FunZone Webpage

### ISSUE THREAD

**Issue by ankit071105** [end3r/Gamedev-Canvas-workshop#19]
# Want to add FunZone Webpage :- 

# Features
In this Webpage it contains more than 30+ games which you can play offline online .
In each Webpage the background Music and the sound effect added. 
In each game restart option and score are there. 

# ScreenShots 

![Screenshot 2024-07-19 at 10 58 12 AM](https://github.com/user-attachments/assets/3f8d48c7-cf59-4a6f-84e9-91498705a4ab)

![Screenshot 2024-07-19 at 10 58 32 AM](https://github.com/user-attachments/assets/557bd768-c671-44f9-a989-b811f1500154)
![Screenshot 2024-07-19 at 10 58 27 AM](https://github.com/user-attachments/assets/db73ae8e-cf38-4a11-82f6-74609b25cb0f)
![Screenshot 2024-07-19 at 10 58 22 AM](https://github.com/user-attachments/assets/874a74e0-b60b-49f2-a2fd-2fe6a1cb97da)

**Comment by end3r** [comment]
This is a workshop material, not a place to advertise your portal with games...
