### ISSUE TITLE
Lesson 5: issue with game over scenario in chrome 

### ISSUE THREAD

**Issue by einsteinreloaded** [end3r/Gamedev-Canvas-workshop#2]
When the ball hits the bottom wall the game over alert pops up infinitely in chrome and the ball sinks into the bottom wall with each alert.

Didn't check in firefox if the issue persists there.

**Comment by diego-asterisk** [comment]
Change 
`   setInterval(draw, 5);   
`
for
`   var game = setInterval(draw, 5);   `

And change
```
          alert("GAME OVER");
          document.location.reload();
```
for 
```
          clearInterval(game);
          alert("GAME OVER");
          document.location.reload();
```

**Comment by end3r** [comment]
Can you please send a Pull Request? I'm more than happy to merge it.

**Comment by end3r** [comment]
PR accepted, thank you!
