### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [end3r/Gamedev-Canvas-workshop#6]
Hello @end3r 

I was reading the Mozilla page and it is says MDN content is under CC-BY-SA (https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses) and the code is public domain, however your repo doesn't also have this license.

Can you add a CC and PD license to your repo as well so people can legally use your repo and the MDN page together?

**Comment by end3r** [comment]
Hey, thanks for bringing this in - sure, sounds like a reasonable request. Can you do a Pull Request with the proper changes?

**Comment by end3r** [comment]
Merged PR, thank you @gdagrow.
