### ISSUE TITLE
Deprecated API call

### ISSUE THREAD

**Issue by milantenk** [end3r/Gamedev-Canvas-workshop#9]
In the `keyDownHandler` and `keyUpHandler` the `KeyboardEvent.keyCode` API is deprecated.
See details here: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

Would you accept a PR that changes the deprecated `KeyboardEvent.keyCode` calls to the recommended `KeyboardEvent.code`?

**Comment by end3r** [comment]
Yes, if you could send a PR I'll gladly accept it, thanks!
